name: CI

on:
  issues:
    types: opened

jobs:
  createissue:
    runs-on: ubuntu-latest
    steps:
      - name: Show all issue information
        env:
          ISSUE_CONTEXT: ${{ toJson(github.event.issue) }}
        run: echo "$ISSUE_CONTEXT"

      
